### ISSUE TITLE
Previous name

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#11]
# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22465923/4af819d8-e7be-11e6-88ab-c3dd9d178cd8.png)

# Hackpad Discussion

https://designpatterns.hackpad.com/Names-mgFWXkwyPEt

**Comment by gavinwye** [comment]
_First pass documentation of the pattern_
_I'm not sure that the order of elements on this page is right at the moment but I'm just trying to get things down on paper at the moment._

### Front matter
_used by middleman_
---
title:      Previous name
section:    Components
theme:      Personal details
status:     Alpha
department: HMRC
---

This guide explains how to ask for people's previous names and is in addition to the guidance on [names](/design-patterns/patterns/components/names/).

### Why we ask for previous names

We need to know when a person has:

* legally changed their name 
* is known by another name

We need to know this because...

* What happens to the data?
* How is the data checked that it's correct?
* What happens if the data is not correct?

### Example

![Example  of a previous name page](previous-name.png)

### Describing the pattern 

This pattern is made up of 4 elements

1. Yes/No question
2. Previous first names
3. Previous middle names
4. Previous last names

### User research

This pattern has been tested with [x] users. This breaks down as:

* [x] moderated usability tests
* [x] number of users have interacted with this pattern in the service during private beta

#### Research overview

During usability testing, users were able to complete this section of the page if there was a need. Users understood the context of the information that the question was being asked and ...

Why are the names plural in the previous names section

### Accessibility

Should accessibility be described here or should  it be described in the code area of the pattern

### Questions to ask before using this pattern

This section is here to help you decide if this pattern is the right thing for you to use in your service.

* Do you really need to know the previous name of the person?
* What will this information be used for in the future?
* What is the consequence of not knowing this information?

### Pattern usage

This pattern is being used in:

* HMRC's [Anti money laundering service](#)

### Pattern support

This pattern is being supported by the [HMRC](#) service design tools as part of the x-gov patterns team. Discuss this pattern on [?Hackpad?](#)

_How would support for this pattern work?
What would HMRC do?
Would people who want to make a contribution to this put in a PR against the pattern in GitHub?
Would people want to talk directly to the team who developed the pattern or would they be happy if all contact was done through the HMRC pattern team/curator_

### Contributors

- [Chris Moffit](#) User research
- [Brian Coult](#) Interaction desigener
- [Phil Sherry](#) Front end development

 _How would contributors like to be attributed?
 > After speaking to Phil Sherry GitHub accounts seem like a good way to attribute users.
 How would be best for contributors to be attributed if we go for an HMRC link we'd loose contact with them if they left the organisation?
 Would attributing them on their personal public GitHub profile be a good thing?_

**Comment by gavinwye** [comment]
Register to vote usage of this pattern
![image](https://cloud.githubusercontent.com/assets/868772/24862419/68d06412-1df4-11e7-8ef8-97d471d478b4.png)

**Comment by stevenaproctor** [comment]
@gavinwye I would be concerned about having fields on the same screen with the same form labels. Is their current name and previous name "one thing"?

Also, the middle names boxes should be optional. Not everyone has middle names.

**Comment by MarkKeeling** [comment]
Happy this is a pattern to add

**Comment by russellthorn** [comment]
Late to this party, but agreed. This is useful, are we sure it's unique?

Nearly all our services use a variant of this for company registration. Asking if the company trades under other names, rather than referring to a persons name change. This definitely has wider uses and would be good to make into a pattern.

**Comment by gavinwye** [comment]
We should mention this in a larger name pattern taking account of #63 

- middle names
- company name
- trading name
