### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#25]
# Description
Money 

# Screenshot
![pla - welcome](https://cloud.githubusercontent.com/assets/2305016/22466491/696625aa-e7b8-11e6-9b94-214aa89736f6.png)

**Comment by gavinwye** [comment]
Alternative approach to displaying currency input

Pound sign outside of the input
![image](https://user-images.githubusercontent.com/868772/27219039-1bcdfacc-5278-11e7-8bb8-c0274c998047.png)

Pound sign inside the input (black rather than gray)
![image](https://user-images.githubusercontent.com/868772/27219174-afe2b45a-5278-11e7-8691-da393e58c8d9.png)

**Comment by stevenaproctor** [comment]
@gavinwye Are all of these accessible? We use the pound sign outside the input. Should there be 3 alternatives?

This is the kind of thing that should be a GOV.UK pattern, along with bank details.

**Comment by stevenaproctor** [comment]
Closed as it is part of the GOV.UK design system backlog.
