### ISSUE TITLE
Check your Answers

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#26]
# Description
Check your Answers

# Screenshot
![pla - welcome](https://cloud.githubusercontent.com/assets/2305016/22466535/a0251e7a-e7b8-11e6-8cb0-683cbd22133c.png)

# Service Manual
https://www.gov.uk/service-manual/design/check-your-answers-pages

**Comment by alex16wake** [comment]
An example from the PAYE journey in SCRS

![image](https://user-images.githubusercontent.com/24815473/28578606-256a4542-7152-11e7-813f-a17f9b969645.png)

**Comment by gavinwye** [comment]
Documenting some questions I've been asked about check your answers.

> Should check your answers be full width or 2/3'rds

This [pull request against the prototype kit](https://github.com/alphagov/govuk_prototype_kit/pull/365/files), made check your answers pages should be 2/3'rds.

> can we can or should we use bold to highlight the Qs (or answers)?

Stick to whatever is in the pattern. Questions in the latest version of the prototype kit are styled bold.

> for accessibility, whether we should be repeating the original page Q in full on the check answers page, or whether we can paraphrase them?

<opinion>I’ve heard rumors about check your answers pages being a summary of questions rather than restating the whole question. But I’ve also heard arguments for the latter. I think if your content design is good enough - short concise questions - I don’t see a problem with restating the question.</opinion> 

> can we use tables for this information?

Only use tables if the information is tabular. The content on a check your answers page is tabular data. The version in the latest prototype kit is a definition list rather than a table.

### Screenshot of the latest check your answers page in the prototype kit 
![image](https://user-images.githubusercontent.com/868772/29829188-a3ddc314-8cd6-11e7-8aef-b8da0c7abb91.png)

**Comment by stevenaproctor** [comment]
The service manual says:

> reword the questions and answers to fit your ‘check your answers’ page - for example, you don’t need to label parts of an address and you can rewrite long questions as shorter statements

If you are asking someone to check or confirm their answers, logically you would show them the question we asked and their answer. If you change a question and an answer you are introducing new content. This could confuse people and will require more cognitive effort to process.

I think doing it this way should be the starting point, and your user research will tell you if the page does not work. In all the user research we have done, people are complimentary about the page.

> Only use tables if the information is tabular. The content on a check your answers page isn't tabular data. The version in the latest prototype kit is a definition list rather than a table.

100% agree about the data not being tabular.

The definition list is incredibly noisy for a screen reader. The personal details section in the screenshot would say something like "list with 12 items" rather than treat each question, answer and link separately.

Some services use divs and another uses a mobile-first, vertically stacked heading, paragraph and link.

**Comment by stevenaproctor** [comment]
Closed as it is part of the GOV.UK design system backlog.
