### ISSUE TITLE
Email address

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#67]
## Screenshot
Collecting email address
![image](https://cloud.githubusercontent.com/assets/868772/22469002/63e5e9bc-e7c2-11e6-9c66-8d0428161525.png)

Collecting email address twice to make sure it's been typed correctly 
![image](https://cloud.githubusercontent.com/assets/868772/22469054/932d7c62-e7c2-11e6-82a5-cbdbbbb15fb7.png)

Verify email address
![image](https://cloud.githubusercontent.com/assets/868772/22469024/742a245a-e7c2-11e6-8c40-80366888cc88.png)

## Other links
Service manual: https://www.gov.uk/service-manual/design/email-addresses
GOV.UK hackpad: https://designpatterns.hackpad.com/Email-addresses-AfMMqnW9E9b
GOV.UK Dropbox paper: https://paper.dropbox.com/doc/Sending-emails-0O9JyksvPiJ0boNda3nKH

**Comment by stevenaproctor** [comment]
@gavinwye The "go paperless" screen will need to stop pre-selecting the yes because of GDPR. From the [Information Commissioner's site](https://ico.org.uk/for-organisations/data-protection-reform/overview-of-the-gdpr/key-areas-to-consider/) (bold is mine):

"Consent under the GDPR must be a freely given, specific, informed and unambiguous indication of the individual’s wishes. There must be some form of clear affirmative action – or in other words, a positive opt-in – **consent cannot be inferred from silence, pre-ticked boxes or inactivity**. Consent must also be separate from other terms and conditions, and you will need to provide simple ways for people to withdraw consent. Public authorities and employers will need to take particular care to ensure that consent is freely given."

**Comment by stevenaproctor** [comment]
This issue was closed because it will be part of the GOV.UK Design System. May need to document the go paperless journey.
