### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#68]
## Screenshot
Drag and drop file upload
![image](https://cloud.githubusercontent.com/assets/868772/22469142/e345b75a-e7c2-11e6-86ea-b7b821fd56b5.png)

Select file - file upload
![image](https://cloud.githubusercontent.com/assets/868772/22469158/f3a2e62c-e7c2-11e6-92bd-b9927ebe62c6.png)

## Other links
GOV.UK elements: http://govuk-elements.herokuapp.com/form-elements/#form-file-upload

**Comment by elizabethbartram** [comment]
![file upload](https://cloud.githubusercontent.com/assets/24933821/22589848/51e3d618-ea04-11e6-84bb-fc7235afac9f.PNG)

**Comment by gavinwye** [comment]
New screenshots of the employment intermediaries service provided by Steven Proctor

![there is a problem](https://cloud.githubusercontent.com/assets/868772/25695424/f0e94328-30aa-11e7-910c-ca39f1dde10a.png)
![upload with error](https://cloud.githubusercontent.com/assets/868772/25695423/f0e887e4-30aa-11e7-9f4a-abc20d328e12.PNG)
![upload](https://cloud.githubusercontent.com/assets/868772/25695422/f0e5af7e-30aa-11e7-8cc0-667e76c09ad6.png)

**Comment by jennifer-hodgson** [comment]
Following our discussions in the working group last week - is file upload (and file download), in fact, a service pattern rather than a pattern?

**Comment by adamliptrot-oc** [comment]
@jennifer-hodgson my view is that if the component parts can be extracted into re-usable patterns, that is fine and those can be documented. There is also a difference in requirements between multiple file upload and single file upload.

**Comment by jennifer-hodgson** [comment]
Thanks for this @adamliptrot-oc. Service patterns are reusable too (they currently exist on a separate backlog, we're discussing how to most usefully house them and make them visible). It seemed to a few of us on the WG call, if I remember correctly, that this was a more complex, multi-step process fulfilling a task which stands as a service pattern. That doesn't preclude, of course, its constituent parts being broken down into useful components and patterns.

**Comment by JamesPBoyle** [comment]
Can I hook you guys into [#event-upscan](https://hmrcdigital.slack.com/messages/C8XPL559N)? UpScan is going to replace File-Upload-as-a-Service. We are still in the process of building the service, but it would be useful to make sure the pattern is consistent with the capabilities of the backend system

**Comment by adamliptrot-oc** [comment]
@jennifer-hodgson yep, I raised that, but keen not to rule out the chance for other services to benefit from the findings of a service built purely to handle this type of interaction. Other services look to be finding their own solutions (outside of a service-based one) so it would be useful to find some common ground between them and document a pattern.

**Comment by jennifer-hodgson** [comment]
Thanks for that, @JamesPBoyle, yes that would be useful. I wonder is this also of interest to @benwakefield?

And thanks for your comments also, @adamliptrot-oc. I think you raise an interesting issue about the relationships between components, design patterns and service patterns, and how to organise and display them within the design system in such a way that everyone who needs a certain thing can find it. Perhaps we could discuss this broader issue at the next working group, @stevenaproctor?

**Comment by stevenaproctor** [comment]
@jennifer-hodgson It is definitely something that needs to be discussed, especially because technical reasons may mean a service-design pattern cannot be implemented as designed. Also, there could be conflicting user research from different services.

**Comment by lfritzsche** [comment]
Large file upload with drag and drop and progress bar
![screenshot-sdes-ux herokuapp com-2018 02 08-09-32-53](https://user-images.githubusercontent.com/23556368/35968306-5e8633ea-0cbb-11e8-8a21-77a96e9ae329.png)
![screenshot-sdes-ux herokuapp com-2018 02 08-09-33-48](https://user-images.githubusercontent.com/23556368/35968307-5e9f776a-0cbb-11e8-885e-bdeab816102b.png)
![screenshot-sdes-ux herokuapp com-2018 02 08-09-36-20](https://user-images.githubusercontent.com/23556368/35968308-5eb49c12-0cbb-11e8-977e-65ee7fe5c5e8.png)
![screenshot-sdes-ux herokuapp com-2018 02 08-09-37-24](https://user-images.githubusercontent.com/23556368/35968311-5f24c460-0cbb-11e8-9f90-79a4de6ab5f3.png)
![screenshot-sdes-ux herokuapp com-2018 02 08-09-40-47](https://user-images.githubusercontent.com/23556368/35968312-5f3a97ae-0cbb-11e8-87c7-6621250c8698.png)
![screenshot-sdes-ux herokuapp com-2018 02 08-09-46-55](https://user-images.githubusercontent.com/23556368/35968313-5f5f3c58-0cbb-11e8-8c42-14895bfacf38.png)

**Comment by lfritzsche** [comment]
This pattern allows users to upload large files to HMRC and understand its status, before during and after transfer.

_Live service:_ This is an invite only service with a prearranged agreement between HMRC for users to send files, so cannot be accessed for general use.
Prototype: https://sdes-ux.herokuapp.com/stable/dashboard/upload 
**Username:** sdes-ux
**Password:** sdes-ux

N.B. To use the upload functionality and recreate different scenarios and their outputs, some dummy files have been created for use with the prototype.

**Dummy files:**
https://drive.google.com/drive/folders/1TTj8FTIEKrhiVwiun9YJO3CRQIjPfDIg?usp=sharing

Name of file: 10gb_804586706943_DWPUC_851.txt
Desired output: Error, file too large

Name of file: cancel_IMAGE20150904001001.txt
Desired output: File cancelled (click cancel whilst it’s uploading to trigger this)

Name of file: ConnErr_SHIP0904ARPA14594402.txt
Desired output: Error, file failed to upload (click retry to try and upload again)

Name of file: valid_P6770_03_001_001_2015_TXT.txt
Desired output: File uploads successfully


**Describe when to use this pattern/component**
_Is it a pattern or component?_ 
Pattern as it uses a combination of different components
_What need does it help you meet?_ 
Allows users to securely send large files to the intended recipient with a record of what happened. 
_When is it appropriate to use?_ 
When there is a need to send documents to a user where alternatives such as email are not appropriate

Not tested with users who upload lots (e.g. 20+ files daily) of small files

**Comment by lfritzsche** [comment]
**How it works**
_Full description_
This upload pattern has been designed to handle the secure transfer of large files from third parties and other government departments to HMRC. It is different to File Upload As A Service (FUUAS) as there are few restrictions on the type and size of files for intended transfer. 

Users can send individual files up to the size of 10GB and any format, excluding executable files (.exe). The pattern allows users to select either individual or multiple files at a time via the main CTA or drag and drop. Once the user has selected the files they wish to upload, there is the opportunity for them to remove (if any have been selected in error) or add new files. Basic checks to ensure selected files are not over 10GB individually or .exe format are done in the backend first so that we can provide appropriate erroring. This allows users to correct any issues with file size and also to mitigate files sent in error.

Errors have been dealt with in a unique way and require further testing from an accessibility and usability perspective within Private Beta. Users must fix the issue before they can proceed to upload by removing the file selected with the issue. This allows users to record the file with the issue in case they need to investigate further. 

The error box at the top of the screen allows users to remove all files with problems, however this may cause usability issues for users with screen readers as they are unable to link to the individual files. They can then continue to upload, which will then launch the uploading functionality.

Uploads in progress is a new component which uses a progress bar in addition to a percentage indicator with the opportunity to cancel any in flight uploads. If users send files that are larger than average, we found that it was important to give the user more visual feedback for the stats of that upload. A similar erroring pattern is used for files with connection errors as previously described. If any errors occur, the user is still able to proceed with the successful files.


_Coded examples_
David Birchall can provide david.birchall@digital.hmrc.gov.uk 

_Why it works_
This pattern works because it is a single page application that gives dynamic inline error messaging when something goes wrong, giving user feedback as to the progress of the upload and individual file control at all stages of the upload process. User research has found that users find this pattern easy to follow with minimal errors encountered.

**Comment by lfritzsche** [comment]
**Research on this pattern**

SDES has just moved into Private Beta from January 29th 2018. Further research is required to understand how users deal with the transfer of large files (2GB and upwards)

All Alpha research can be found here: https://confluence.tools.tax.service.gov.uk/display/SDES/Alpha+Research


**Feature specific research summary:**
Real time feedback such as error messages and status (failed, cancelled, complete) - 
Dynamic components - The upload journey uses a single page which uses JS to dynamically change components based on the scenario. This tested very well with users and they found the additional info, inline errors and individual control very intuitive. Further testing is required for large batches of files uploaded at once.

User control before and during upload - This tested well in alpha, although users  didn’t have actual reasons to cancel and retry as they were using dummy files with the prototype. More extensive contextual research is required in Private Beta.

Multi file uploads - Most of our users selected single files to upload. Multi file uploads were useful for those uploading on behalf of their organisation, however within that group only those with a higher technical proficiency used the drag and drop functionality. This is why the design reflects drag and drop as a secondary action.

10GB per individual files - this needs to be extensively tested via contextual enquiry within Private beta. The prototype and the machines we tested on were super efficient and potentially don’t give an accurate reflection of the time it actually takes to upload files. Best practice stipulates around 1GB per file for efficient browser uploading.

**Comment by jennifer-hodgson** [comment]
[Published](https://design-system.service.gov.uk/components/file-upload/) in the GOV.UK Design System.

**Comment by stevenaproctor** [comment]
The GOV.UK Design System is a file upload component for a single file. The examples on the page include drag and drop methods for single and multiple files. We should delete our issue and contribute to the Design System.

**Comment by mikeash82** [comment]
Contributions moved to [File upload](https://github.com/alphagov/govuk-design-system-backlog/issues/49) on the GOV.UK issues backlog
