### ISSUE TITLE
What happens next

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#8]
# Description

Useful information or links on what to do after completing a journey

# Screenshot

![image](https://cloud.githubusercontent.com/assets/1752124/22465354/9302b344-e7bb-11e6-8ee9-3439205dda1d.png)

**Comment by stevenaproctor** [comment]
@gavinwye Part of confirmation page patter. https://www.gov.uk/service-manual/design/confirmation-pages

**Comment by rpowis** [comment]
@stevenaproctor Does this appear anywhere else?

1. If it does then it more likely a component.
2. If it doesn't and our confirmation pages are identical to GOV.UK's then we can close this issue.
3. If HMRC confirmation pages differ from GOV.UK's (for good reason of course) then the scope of this issue should be expanded to include the rest of the Confirmation page pattern.

**Comment by stevenaproctor** [comment]
@rpowis I have never seen it anywhere else. It would only come after you have done something so it makes sense to part of the confirmation page.

Confirmation pages can differ from service to service but they are variations on a theme. Some services have a section called "What you can do next" but I doubt we would want a pattern for them.

It would make more sense to build on the GOV.UK pattern to include variations, rather than have our own.

**Comment by rpowis** [comment]
> It would make more sense to build on the GOV.UK pattern to include variations, rather than have our own.

That still requires putting those variations in our pattern library. Which is fine, we just need to expand the scope of this ticket to encompass those variations as full patterns then.

**Comment by gavinwye** [comment]
this is part of the confirmation pattern
