### ISSUE TITLE
Cookie page

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#88]
## Description
This page tells people how we use cookies.

It's linked to #87 

## Screenshot

To do

## Research
Do all services use the same cookie message?
What is the user need for this?

**Comment by gavinwye** [comment]
Where do we list service specific cookie messages?

**Comment by stevenaproctor** [comment]
I am not sure we do. There is no accepted

https://www.tax.service.gov.uk/help/cookies is the page for the platform page.

I was told to have a specific employment intermediaries page so we wrote one based on cookies in the service and platform at that time. I found a lot on the platform page that we did not use so I removed them from the page. I do not think it has been updated since. See https://www.tax.service.gov.uk/employment-intermediary-report/cookies
